### ISSUE TITLE
wpcli diff returning invalid argument supplied for foreach

### ISSUE THREAD

**Issue by gilzow** [forumone/wp-cfm#100]
[Posted](https://wordpress.org/support/topic/wpcli-diff-returning-invalid-argument-supplied-for-foreach/) this over in the WordPress support forums but didn't get response so thought I'd try here. 

Changed the configuration file location via `add_filter('wpcfm_config_dir', <function>)`, and changed file type to yaml via `add_filter('wpcfm_config_format', <function>)`. Attempting to use wpcli commands to diff. Both `wp config push <bundle>` and `wp config pull <bundle>` work correctly. If I do `wp config diff <bundle>` and the values in the db are identical to the values in the config file, then I get the expected Warning: Both versions are identical. However, if the configuration file is changed and I attempt to do `wp config diff <bundle>` I receive the error:

```
PHP Warning:  Invalid argument supplied for foreach() in /app/web/wp-content/mu-plugins/wp-cfm/includes/class-wp-cli.php on line 92
PHP Warning:  Invalid argument supplied for foreach() in /app/web/wp-content/mu-plugins/wp-cfm/includes/class-wp-cli.php on line 100
```

If I debug the contents of $compare at those lines, it contains a linefeed separated string of my configuration values, not an array of values as expected.

SAMPLE:

```
cache_control_attachment_max_age: \'10800\'
cache_control_attachment_staleerror: \'10800\'
cache_control_attachment_stalereval: \'10800\'
cache_control_attachment_s_maxage: \'5400\'
```

Running Diff in the web gui returns the expected differences.

I’ll also mention that the yaml file passes a yaml lint check. I also put the config file type back to json, converted the yaml data to json and created a json bundle. The exact same scenario as described above happens. Everything works correctly until the data in the config differs from the db and I run a diff from the CLI.

WordPress is version 5.2.1.
WP-CFM is version 1.5.1.
PHP is version 7.2.19

Running WP-CFM as a must-use plugin.

Any ideas on why this is breaking?

**Comment by gilzow** [comment]
tangentially related, if I spin up a site where the bundle file is present, but no db entry has been created yet and do a diff from the CLI, I also get a WARNING for class-readwrite.php

`PHP Warning: Invalid argument supplied for foreach() in /app/web/wp-content/mu-plugins/wp-cfm/includes/class-readwrite.php on line 261`

In looking at the code, line 259 is going to retrieve the options for wpcfm_settings. Since it isn’t set yet, get_option() is going to return a boolean false. a json_decode() on a boolean false at line 260 is going to return NULL. Hence the error at 261.

Doing `wp config bundles` shows the bundle and notes it is not in the DB. Is there a way to retrieve just the `In DB` column+value for a bundle? If so, I could just check that before attempting a diff. I had just assumed running a diff when the values aren’t in the db would say there’s a diff and then I could pull the bundle into the db.

**Comment by gilzow** [comment]
Dug into this some more.  Looks like the issue is with `WPCFM_Readwrite::compare_bundle` at [line 150](https://github.com/forumone/wp-cfm/blob/master/includes/class-readwrite.php#L150). You convert the bundles to a string (yaml) before doing a comparison between the db and the files, but then you don't convert the string back to an array before returning at the end of the method.  

`WPCFM_CLI::diff` is expecting the return from `WPCFM()->readwrite->compare_bundle()` to be an array at [line 92](https://github.com/forumone/wp-cfm/blob/master/includes/class-wp-cli.php#L92).

The only other location that calls `WPCFM()->readwrite->compare_bundle()` appears to be `WPCFM_Ajax::load_diff()` at [line 56 ](https://github.com/forumone/wp-cfm/blob/master/includes/class-ajax.php#L56) which does a `print_r()` on the return. 

I'll submit a fix via PR here in a minute.

**Comment by gilzow** [comment]
Submitted merge request #101

**Comment by elvismdev** [comment]
@gilzow Somehow we merged a fix for this in https://github.com/forumone/wp-cfm/pull/124.

You can still improve your proposed solution and submit new changes!
