### ISSUE TITLE
Warning: Use of undefined constant WP_HOME

### ISSUE THREAD

**Issue by screid123** [forumone/wp-cfm#113]
A warning is seen when sending commands via the WP-CLI when WP_HOME isn't defined in `wp-config.php`:

>Warning: Use of undefined constant WP_HOME - assumed 'WP_HOME' (this will throw an Error in a future version of PHP) in /app/wp-content/plugins/wp-cfm/wp-cfm.php on line 65

This is on Pantheon-hosted environment using PHP 7.3 and WordPress 5.2.4.

**Comment by screid123** [comment]
I realize this may be unique to `wp-config.php` setups, but is the assumption that if on a Pantheon environment that `WP_HOME` will always be set by their boilerplate config?

**Comment by kyletaylored** [comment]
I found this same issue as well when running a WP CLI plugin. Submitted a PR for the fix.
