### ISSUE TITLE
Slow pull for large wp_options table

### ISSUE THREAD

**Issue by fariasf** [forumone/wp-cfm#116]
Hi!

I'm using the plugin on a site that tracks 23 bundles, and that was affected by [a bug](https://wordpress.org/support/topic/_wp_session-wp_options/), ending up with more than 500K rows in its wp_options table. Running `wp config pull all` on that site took more than 30 minutes.

After cleaning up wp_options down to 5K rows, times went down:
```
$ time wp config pull all
Success: The bundle has been pulled into the database.
real	3m43.456s
user	0m1.070s
sys	0m0.175s
```

Trying to improve these numbers, I found [`WPCFM_Readwrite::write_db` runs `foreach ( $bundles ... )`](https://github.com/forumone/wp-cfm/blob/363cdd3bcb0d7585ce4ddbc4cea3d5550d33b4a8/includes/class-readwrite.php#L50) and calls [`WPCFM_Registry::get_configuration_items`](https://github.com/forumone/wp-cfm/blob/363cdd3bcb0d7585ce4ddbc4cea3d5550d33b4a8/includes/class-registry.php#L18-L45,) which loads all options into memory.

I've patched the code so that `get_configuration_items` is called only once, storing the value in a static class-level variable, and got the following results:

```
$ time wp config pull all
Success: The bundle has been pulled into the database.
real    0m19.811s
user    0m1.073s
sys    0m0.172s
```

For my use case, it looks like nothing is broken, but I wonder...
- Am I on the right track?
- What possible side effects may this cause?
- Are there any tests I can run?

I can send a Pull Request with the change if that's helpful.

Thanks!

**Comment by elvismdev** [comment]
Hi @fariasf , you are welcome to send a PR of course! It seems like a good improvement so we would like to review and test it. This plugin does't include unit tests yet.
