### ISSUE TITLE
FILTER_SANITIZE_STRING is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by gbeezus** [forumone/wp-cfm#135]
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/html/web/wp-content/plugins/wp-cfm/wp-cfm.php on line 121 after installing WP-CFM with PHP 8.1.

Also occurs on line [129](https://github.com/forumone/wp-cfm/blob/develop/wp-cfm.php#L129) and [254](https://github.com/forumone/wp-cfm/blob/develop/wp-cfm.php#L254) in wp-cfm.php.

**Comment by timnolte** [comment]
@tropicandid FYI, as we are working to start rolling out PHP 8.1 upgrade we need to get this fixed. I'm going to get WP-CFM back on my priority list and work on getting this mitigates as soon as possible.

**Comment by timnolte** [comment]
PHP 8.1 upgrade visibility: https://forumone.atlassian.net/wiki/spaces/support/pages/3596943507/PHP+8.0+to+8.1+Compatibility#WP-CFM

**Comment by timnolte** [comment]
Looks like another related item when doing a `wp config pull all`:
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/web/wp-content/plugins/wp-cfm/vendor/symfony/yaml/Inline.php on line 86
```

**Comment by timnolte** [comment]
For the original issue there is a "polyfill" function that can be used:
```php
function filter_string_polyfill(string $string): string
{
    $str = preg_replace('/\x00|<[^>]*>?/', '', $string);
    return str_replace(["'", '"'], ['&#39;', '&#34;'], $str);
}
```

**Comment by gbeezus** [comment]
@timnolte Willing to talk it out. I'm not convinced that the precise polyfill you provided is enough to replicate what was done previously with `FILTER_SANITIZE_STRING` which also encoded a fair amount. Are we considering whether we need the same functionality for comparing input to environment variable strings? Maybe I am misunderstanding something here.

**Comment by timnolte** [comment]
@gbeezus actually, looking at the code that was written I did discover that it is wrong as the original got was looking at `INPUT_GET` & `INPUT_POST`. The code that was implemented incorrectly use `$_GET` twice.

**Comment by gbeezus** [comment]
@timnolte. You took a deeper dive into the code. Great. That was a good move. 

I saw that post before you linked it out again and I thought better of trying to point out that blindly copying code from StackOverflow instead of critically looking at what you had is dangerous. Maybe my solution wasn't right but the overall gist of what I read there was that we need to tailor it to what we need.

**Comment by timnolte** [comment]
@gbeezus just to be clear I wasn't "blindly" copying anything.
