### ISSUE TITLE
403 returned on ajax requests - nonce is not being sent (admin.min.js is not updated to latest)

### ISSUE THREAD

**Issue by tych095** [forumone/wp-cfm#176]
**Describe the bug**
Version 1.7.9 of the plugin gets a 403 for every request to admin-ajax.php is called. I checked admin.js, the nonce is sent, however it doesn't look like its being sent in admin.min.js (perhaps it needs to be re-minified).

Using the non-minified admin.js seems to resolve the issue.

**To Reproduce**
1. Activate plugin
2. Attempt any operation
3. See error in dev console

**Screenshots**

**Expected behavior**
403 is not returned

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only this plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- Website URL: 
- PHP Version: 8.0.8
- WordPress Version: 6.4.3
- Plugin Version: 1.7.9

**Comment by timnolte** [comment]
@tych095 thanks for this report! It looks like our build and release process isn't properly minifying assets.

**Comment by timnolte** [comment]
@tropicandid & @jgleisner looks like this might be our problem, and the Dev Container is loading up the unminified version.

**Comment by timnolte** [comment]
@tych095 version 1.7.10 was just released and this issue should be fixed now.
