### ISSUE TITLE
wp-cfm and data saved into other table

### ISSUE THREAD

**Issue by nonchiedercilaparola** [forumone/wp-cfm#39]
Can someone tell me more about this opinion about wp-cfm?

“WP-CFM will be handy if you assume all your configuration settings are in the options table, in very simple key value pairs.This assumption is risky, I’ve seen so many plugin developers build their plugin to save settings in all kinds of ways that I can’t safely assume that config will actually be in the options table.”

**Comment by arh1** [comment]
@nonchiedercilaparola wp-cfm support config stored in the options table "out of the box". For other configuration, you'll need to write integration w/ wp-cfm by implementing the wpcfm_configuration_items hook. Check out http://forumone.github.io/wp-cfm/ for documentation.
