### ISSUE TITLE
Merge taxonomy support branch to fix premature return for taxo items

### ISSUE THREAD

**Issue by dotdotfx** [forumone/wp-cfm#50]
I was wondering why taxonomies from my custom post types are not showing up in the bundle screens. Turns out that WPCFM_Taxonomy->configuration_items() in https://github.com/forumone/wp-cfm/blob/master/includes/integrations/taxonomy.php returns the $items array prematurely (within the foreach loop from line 18), so that it only includes the first taxonomy.

This is fixed in the branch taxonomy-support (https://github.com/forumone/wp-cfm/blob/taxonomy-support/includes/integrations/taxonomy.php), but has been stale since Dec 19th, 2014. The taxonomy-support branch seems to contain SQL instead of WP functions, so might be best to just fix this in the master branch.

Let me know if I should open a PR :-) And thanks for this great plugin!

**Comment by mgibbs189** [comment]
Hi, what priority is the init hook that your CPTs / taxonomies are being registered with?

**Comment by dotdotfx** [comment]
Hi Matt,
haven't set one, so default pritority = 10. I also tried giving both init hooks a priority of 1 and reverted taxonomy.php to the current stable release (with the return within the foreach loop), but the taxonomy still didn't show up.
When I move the return outside the foreach loop, all taxonomies including my custom one show up in the WP-CFM bundle management screen.
