### ISSUE TITLE
Add push option to specify destination

### ISSUE THREAD

**Issue by mortona42** [forumone/wp-cfm#51]
Workflow for creating and pushing a bundle outside of default directory:
1. Create bundle in UI. (this doesn't create a file until you push)
2. Push using --destination in CLI
3. Commit bundle to git.
4. Deploy, pull using --source.

Assumptions:
1. If a different location is specified, remove the original file.  If you're moving a bundle out of the default directory, this will prevent it from being detected in two places.

This is slightly different than https://github.com/forumone/wp-cfm/issues/38.  Please drop a comment below if you have any comments/suggestions.

**Comment by arh1** [comment]
A few other assumptions:

* A path is stored in the db with the bundle data
* The path is used for both the push destination and pull source unless a new path is specified explicitly as an argument on one of those commands, which will update the path in the db
* Paths are relative to the site root (not absolute, and not relative to the config directory)
