### ISSUE TITLE
php7 issue with callbacks

### ISSUE THREAD

**Issue by eriktorsner** [forumone/wp-cfm#60]
When using wp-cfm from the command line. I get the following error under php7:

Uncaught Error: Function name must be a string in /vagrant/www/wordpress-default/wp-content/plugins/wp-cfm/includes/class-readwrite.php:277

The issue is fixed by changing line 277 from:
$success = $callback[0]->$callback[1]( $callback_params );
to:
$success = call_user_func($callback, $callback_params);

Perhaps line 280 would also need to be changed, haven't figured out how to test it though.

**Comment by mgibbs189** [comment]
@eriktorsner Thanks for the report. I'll look at it shortly

**Comment by mgibbs189** [comment]
Closing, looks to have been fixed already with cd0a0d7
