### ISSUE TITLE
Managing passwords and other secrets

### ISSUE THREAD

**Issue by eriktorsner** [forumone/wp-cfm#63]
Hi, Consider this more of a discussion topic than a bug or feature request. 

I'm looking for a way to avoid accidentally managing secrets with WP-CFM. 

My scenario is a WordPress site that uses one or more plugins where part of what goes into the options table are secrets. Typically this would be credentials for 3rd party services like external email providers, Stripe, PayPal or whatever. Some DevOps people would ague (and I would agree) that it's not a good idea to add secrets to the Git repo. Sometimes the secret stuff is stored on a separate row in the options table, sometimes they might be part of a larger array.

Anyone that tried to solve this problem before? Ideas?

**Comment by mgibbs189** [comment]
@eriktorsner good question. I agree that sensitive info should stay out of git, but I'm not sure there's any good automated solutions.

One idea would be to use a meta key "blacklist", but that could become a maintainability nightmare...

**Comment by arh1** [comment]
We could consider what it would take to integrate wp-cfm with key management services like [Lockr](https://lockr.io/).

**Comment by eriktorsner** [comment]
Lockr would be one interesting alternative But I think a self-hosted alternative is still important in the WP community (even if the acceptance of external SaaS solutions seem to grow by the day). Ideally, a native WP-CFM solution could use more than one service provider for the secrets. Lockr could be one of them.

I'm working with dotenv files in a few projects. One of the benefits with dotenv is that there seem to be a lot of acceptance for it in the DevOps community. Dotenv has some downsides, but it's a step in the right direction. With acceptance comes tools and processes, so I'm leaning towards a solution using dotenv to solve my immediate needs.

A few pre- and post-processing scripts that changes the content of WP-CFM files will do the trick, but that would mean building an infrastructure outside WP-CFM. In scenarios where proper deployment scripts already exists, it won't be a big deal. But it would be nice to come up with a "native" solution so that WP-CFM is aware of what's going on.
