### ISSUE TITLE
Deploy releases to WordPress.org with GitHub Actions

### ISSUE THREAD

**Issue by ataylorme** [forumone/wp-cfm#94]
[This article](https://github.com/10up/actions-wordpress/blob/develop/dotorg-plugin-deploy/README.md) is a good start

**Comment by elvismdev** [comment]
@ataylorme we now have GitHub Actions! 

![Screen Shot 2019-08-20 at 3 33 30 PM](https://user-images.githubusercontent.com/3847077/63390843-519f0500-c365-11e9-84f8-682ad98fa36e.png)

**Comment by elvismdev** [comment]
@ataylorme This is now set! And v1.6 pushed to https://wordpress.org/plugins/wp-cfm

![Screen Shot 2019-08-30 at 10 43 32 AM](https://user-images.githubusercontent.com/3847077/64041844-560daf80-cb15-11e9-8e87-2466356ecf8d.png)

**Comment by ataylorme** [comment]
That’s awesome!
