### ISSUE TITLE
WordPress 5.0 Testing/Support

### ISSUE THREAD

**Issue by ataylorme** [forumone/wp-cfm#96]
Done when https://wordpress.org/plugins/wp-cfm/ is tested up to the latest version of WordPress and no longer shows an out of date warning

**Comment by elvismdev** [comment]
@ataylorme Plugin has been tested on latest WP v5.2.1 and updated in the WP.org repo. Warning is no longer showing up now https://wordpress.org/plugins/wp-cfm/#developers
