### ISSUE TITLE
Thorough Documentation

### ISSUE THREAD

**Issue by ataylorme** [forumone/wp-cfm#99]
* Code comments
* Requirements, tested up to, etc.
* All functions, filters, options, documented
* Top notch examples
* Basic tutorial
* Changelog (SemVer, link to issues/PRs)
* Roadmap

Existing code can have documentation added over time. All new features or pull requests should have accompanying documentation.

**Comment by elvismdev** [comment]
@ataylorme All the available plugin filters are now documented here: https://github.com/forumone/wp-cfm/wiki/Filters-Reference

**Comment by ataylorme** [comment]
@elvismdev https://github.com/forumone/wp-cfm/wiki/Filters-Reference looks great! The code samples are 👍.

I think once #104 and #105 are merged we can proceed with CHANGELOG updates and releasing a new version.

**Comment by elvismdev** [comment]
Wiki pages updated:
- https://github.com/forumone/wp-cfm/wiki/WP-CLI-Commands-Reference
- https://github.com/forumone/wp-cfm/wiki/Multiple-Environments-Configuration
